[package]
name = "service_1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
sqlx.workspace = true

# [env]
# DATABASE_URL = "postgres://postgres:postgres@localhost:5432/test_db_1"
